"""CGDE-NSGA-II: NSGA-II with cross-generation differential evolution."""

from __future__ import annotations

from collections.abc import Callable

import numpy as np

from .core import ProblemAdapter, resize_initial_population
from .nsga2 import environmental_selection, rank_and_crowding
from .operators import cgde_offspring


class CGDE_NSGAII:
    """
    NSGA-II using cross-generation differential evolution.

    Offspring are generated by current-to-pbest/1 DE where one difference vector
    endpoint is sampled from an archive of previous generations. This gives the
    DE operator explicit cross-generation memory while survival remains standard
    NSGA-II environmental selection.
    """

    def __init__(
        self,
        problem: ProblemAdapter,
        pop_size: int = 100,
        n_gen: int = 200,
        F: float = 0.5,
        CR: float = 0.9,
        pbest_ratio: float = 0.2,
        archive_size_factor: float = 1.0,
        mutation_prob: float | None = None,
        eta_m: float = 20.0,
        seed: int | None = None,
    ) -> None:
        self.problem = problem
        self.pop_size = int(pop_size)
        self.n_gen = int(n_gen)
        self.F = float(F)
        self.CR = float(CR)
        self.pbest_ratio = float(pbest_ratio)
        self.archive_size_factor = float(archive_size_factor)
        self.mutation_prob = mutation_prob
        self.eta_m = float(eta_m)
        self.rng = np.random.default_rng(seed)

        self.population: np.ndarray | None = None
        self.objectives: np.ndarray | None = None
        self.archive: np.ndarray | None = None
        self.history: list[np.ndarray] = []

    def run(
        self,
        initial_x: np.ndarray | None = None,
        progress_callback: Callable[[int, int], None] | None = None,
    ) -> tuple[np.ndarray, np.ndarray]:
        if initial_x is None:
            P = self.rng.uniform(self.problem.xl, self.problem.xu, size=(self.pop_size, self.problem.n_var))
        else:
            P = resize_initial_population(initial_x, self.pop_size, self.problem.xl, self.problem.xu, self.rng)

        F_values = self.problem.evaluate(P)
        ranks, crowding, _ = rank_and_crowding(F_values)
        archive = P.copy()
        self.history.clear()

        mutation_prob = (1.0 / self.problem.n_var) if self.mutation_prob is None else float(self.mutation_prob)

        for generation in range(1, self.n_gen):
            previous_population = P.copy()
            offspring = np.asarray(
                [
                    cgde_offspring(
                        idx,
                        P,
                        ranks,
                        crowding,
                        archive,
                        self.F,
                        self.CR,
                        self.pbest_ratio,
                        self.problem.xl,
                        self.problem.xu,
                        self.rng,
                        mutation_prob=mutation_prob,
                        eta_m=self.eta_m,
                    )
                    for idx in range(self.pop_size)
                ],
                dtype=float,
            )
            offspring_F = self.problem.evaluate(offspring)

            combined_P = np.vstack([P, offspring])
            combined_F = np.vstack([F_values, offspring_F])
            P, F_values, ranks, crowding = environmental_selection(combined_P, combined_F, self.pop_size)
            archive = self._update_archive(archive, previous_population)

            self.history.append(F_values.copy())
            if progress_callback is not None:
                progress_callback(generation + 1, self.n_gen)

        self.population = P
        self.objectives = F_values
        self.archive = archive
        return P, F_values

    def result_X(self) -> np.ndarray:
        self._require_run()
        return self.population.copy()

    def result_F(self) -> np.ndarray:
        self._require_run()
        return self.objectives.copy()

    def _update_archive(self, archive: np.ndarray, previous_population: np.ndarray) -> np.ndarray:
        max_size = max(1, int(round(self.pop_size * self.archive_size_factor)))
        merged = np.vstack([archive, previous_population])
        if len(merged) <= max_size:
            return merged
        selected = self.rng.choice(len(merged), size=max_size, replace=False)
        return merged[selected].copy()

    def _require_run(self) -> None:
        if self.population is None or self.objectives is None:
            raise RuntimeError("run() must be called first")

