"""
Create delta tables versus the full improved model for ablation studies.

Input:
- benchmark_summary_ablation.csv (or any summary CSV generated by benchmark.py)

Outputs:
- ablation_delta_vs_full.csv                 (per-problem detail)
- ablation_delta_vs_full_overall.csv         (average delta across problems)
- ablation_delta_vs_full.md                  (markdown table for report)
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np


DEFAULT_SUMMARY_CSV = "outputs/benchmark_summary_ablation.csv"
DEFAULT_OUTPUT_DIR = "outputs"
DEFAULT_FULL_MODEL = "improved_nsga2"
DEFAULT_ABLATION_PREFIX = "improved_nsga2_ablation_"
DEFAULT_OUTPUT_PREFIX = "ablation"


def _safe_pct(delta: float, base: float) -> float:
    if np.isclose(base, 0.0):
        return float("nan")
    return float(100.0 * delta / base)


def _load_summary_rows(path: str) -> List[Dict[str, object]]:
    rows: List[Dict[str, object]] = []
    with open(path, "r", newline="", encoding="utf-8") as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            rows.append(
                {
                    "problem": row["problem"],
                    "algorithm": row["algorithm"],
                    "hv_mean": float(row["hv_mean"]),
                    "igd_mean": float(row["igd_mean"]),
                    "runtime_mean": float(row.get("runtime_mean", "nan")),
                    "igd_plus_mean": float(row.get("igd_plus_mean", row["igd_mean"])),
                    "epsilon_additive_mean": float(row.get("epsilon_additive_mean", row["igd_mean"])),
                    "spacing_mean": float(row.get("spacing_mean", "nan")),
                }
            )
    return rows


def _build_lookup(rows: List[Dict[str, object]]) -> Dict[Tuple[str, str], Dict[str, object]]:
    return {(str(r["problem"]), str(r["algorithm"])): r for r in rows}


def build_delta_tables(
    rows: List[Dict[str, object]],
    full_model: str,
    ablation_prefix: str,
) -> tuple[List[Dict[str, object]], List[Dict[str, object]]]:
    problems = sorted({str(r["problem"]) for r in rows})
    algorithms = sorted({str(r["algorithm"]) for r in rows})

    ablation_algorithms = [a for a in algorithms if a.startswith(ablation_prefix)]
    if not ablation_algorithms:
        raise ValueError(f"No ablation algorithms found with prefix: {ablation_prefix}")

    lookup = _build_lookup(rows)
    detail_rows: List[Dict[str, object]] = []

    for problem in problems:
        full_key = (problem, full_model)
        if full_key not in lookup:
            continue

        full_row = lookup[full_key]
        full_hv = float(full_row["hv_mean"])
        full_igd = float(full_row["igd_mean"])
        full_runtime = float(full_row["runtime_mean"])

        for algo in ablation_algorithms:
            key = (problem, algo)
            if key not in lookup:
                continue

            row = lookup[key]
            hv = float(row["hv_mean"])
            igd = float(row["igd_mean"])
            runtime = float(row["runtime_mean"])

            delta_hv = hv - full_hv
            delta_igd = igd - full_igd
            delta_runtime = runtime - full_runtime

            detail_rows.append(
                {
                    "problem": problem,
                    "full_model": full_model,
                    "ablation_algorithm": algo,
                    "hv_mean_full": full_hv,
                    "hv_mean_ablation": hv,
                    "delta_hv_abs": delta_hv,
                    "delta_hv_pct": _safe_pct(delta_hv, full_hv),
                    "hv_improvement_abs": delta_hv,
                    "hv_improvement_pct": _safe_pct(delta_hv, full_hv),
                    "igd_mean_full": full_igd,
                    "igd_mean_ablation": igd,
                    "delta_igd_abs": delta_igd,
                    "delta_igd_pct": _safe_pct(delta_igd, full_igd),
                    "igd_improvement_abs": -delta_igd,
                    "igd_improvement_pct": _safe_pct(-delta_igd, full_igd),
                    "runtime_mean_full": full_runtime,
                    "runtime_mean_ablation": runtime,
                    "delta_runtime_abs": delta_runtime,
                    "delta_runtime_pct": _safe_pct(delta_runtime, full_runtime),
                }
            )

    if not detail_rows:
        raise ValueError("No comparable rows found between full model and ablation algorithms")

    overall_rows: List[Dict[str, object]] = []
    for algo in ablation_algorithms:
        algo_rows = [r for r in detail_rows if str(r["ablation_algorithm"]) == algo]
        if not algo_rows:
            continue

        hv_delta_abs = np.array([float(r["delta_hv_abs"]) for r in algo_rows], dtype=float)
        igd_delta_abs = np.array([float(r["delta_igd_abs"]) for r in algo_rows], dtype=float)
        runtime_delta_abs = np.array([float(r["delta_runtime_abs"]) for r in algo_rows], dtype=float)
        hv_impr_abs = np.array([float(r["hv_improvement_abs"]) for r in algo_rows], dtype=float)
        igd_impr_abs = np.array([float(r["igd_improvement_abs"]) for r in algo_rows], dtype=float)

        hv_delta_pct = np.array([float(r["delta_hv_pct"]) for r in algo_rows], dtype=float)
        igd_delta_pct = np.array([float(r["delta_igd_pct"]) for r in algo_rows], dtype=float)
        runtime_delta_pct = np.array([float(r["delta_runtime_pct"]) for r in algo_rows], dtype=float)
        hv_impr_pct = np.array([float(r["hv_improvement_pct"]) for r in algo_rows], dtype=float)
        igd_impr_pct = np.array([float(r["igd_improvement_pct"]) for r in algo_rows], dtype=float)

        overall_rows.append(
            {
                "full_model": full_model,
                "ablation_algorithm": algo,
                "n_problems": len(algo_rows),
                "delta_hv_abs_mean": float(np.mean(hv_delta_abs)),
                "delta_hv_pct_mean": _nanmean_or_nan(hv_delta_pct),
                "hv_improvement_abs_mean": float(np.mean(hv_impr_abs)),
                "hv_improvement_pct_mean": _nanmean_or_nan(hv_impr_pct),
                "delta_igd_abs_mean": float(np.mean(igd_delta_abs)),
                "delta_igd_pct_mean": _nanmean_or_nan(igd_delta_pct),
                "igd_improvement_abs_mean": float(np.mean(igd_impr_abs)),
                "igd_improvement_pct_mean": _nanmean_or_nan(igd_impr_pct),
                "delta_runtime_abs_mean": float(np.mean(runtime_delta_abs)),
                "delta_runtime_pct_mean": _nanmean_or_nan(runtime_delta_pct),
            }
        )

    return detail_rows, overall_rows


def _write_csv(path: Path, rows: List[Dict[str, object]]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return

    fieldnames = list(rows[0].keys())
    with open(path, "w", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _nanmean_or_nan(arr: np.ndarray) -> float:
    valid = arr[~np.isnan(arr)]
    if valid.size == 0:
        return float("nan")
    return float(np.mean(valid))


def _to_markdown_table(rows: List[Dict[str, object]]) -> str:
    if not rows:
        return "No rows"

    headers = [
        "ablation_algorithm",
        "n_problems",
        "hv_improvement_abs_mean",
        "hv_improvement_pct_mean",
        "igd_improvement_abs_mean",
        "igd_improvement_pct_mean",
        "delta_runtime_abs_mean",
        "delta_runtime_pct_mean",
    ]

    lines = []
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("| " + " | ".join(["---"] * len(headers)) + " |")

    for row in rows:
        values = []
        for h in headers:
            v = row[h]
            if isinstance(v, float):
                values.append(f"{v:.6f}")
            else:
                values.append(str(v))
        lines.append("| " + " | ".join(values) + " |")

    return "\n".join(lines)


def create_delta_report(
    summary_csv: str,
    output_dir: str,
    full_model: str,
    ablation_prefix: str,
    output_prefix: str,
) -> None:
    rows = _load_summary_rows(summary_csv)
    detail_rows, overall_rows = build_delta_tables(rows, full_model=full_model, ablation_prefix=ablation_prefix)

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    safe_prefix = output_prefix.strip() or DEFAULT_OUTPUT_PREFIX
    detail_path = out_dir / f"{safe_prefix}_delta_vs_full.csv"
    overall_path = out_dir / f"{safe_prefix}_delta_vs_full_overall.csv"
    markdown_path = out_dir / f"{safe_prefix}_delta_vs_full.md"

    _write_csv(detail_path, detail_rows)
    _write_csv(overall_path, overall_rows)

    markdown_text = "# Ablation Delta vs Full Model\n\n"
    markdown_text += f"Full model: `{full_model}`\n\n"
    markdown_text += "## Overall (average across problems)\n\n"
    markdown_text += _to_markdown_table(overall_rows)
    markdown_text += "\n"
    markdown_path.write_text(markdown_text, encoding="utf-8")

    print(f"Saved detail delta CSV: {detail_path}")
    print(f"Saved overall delta CSV: {overall_path}")
    print(f"Saved markdown table: {markdown_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build delta table vs full model for ablation summary CSV")
    parser.add_argument("summary_csv", nargs="?", default=DEFAULT_SUMMARY_CSV, help="Path to benchmark summary CSV")
    parser.add_argument("--output-dir", default=DEFAULT_OUTPUT_DIR, help="Output directory")
    parser.add_argument("--full-model", default=DEFAULT_FULL_MODEL, help="Algorithm name treated as full model")
    parser.add_argument(
        "--ablation-prefix",
        default=DEFAULT_ABLATION_PREFIX,
        help="Prefix used to identify ablation algorithms",
    )
    parser.add_argument(
        "--output-prefix",
        default=DEFAULT_OUTPUT_PREFIX,
        help="Prefix for output filenames",
    )
    args = parser.parse_args()

    create_delta_report(
        summary_csv=args.summary_csv,
        output_dir=args.output_dir,
        full_model=args.full_model,
        ablation_prefix=args.ablation_prefix,
        output_prefix=args.output_prefix,
    )


if __name__ == "__main__":
    main()
